title: 自動食記
description: 写真から食事を自動で記録・振り返れる iOS アプリ
url: https://moriyatee.github.io
baseurl: /jidoshokki-privacy-policy

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
